// Auth
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const USER_RESET = 'USER_RESET'
export const USER_LOGOUT = 'USER_LOGOUT'


// Tasks
export const GET_ALL_TASKS = 'GET_ALL_TASKS'
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS'
export const GET_ALL_TASKS_ERROR = 'GET_ALL_TASKS_ERROR'

export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const ADD_NEW_TASK_SUCCESS = 'ADD_NEW_TASK_SUCCESS'
export const ADD_NEW_TASK_ERROR = 'ADD_NEW_TASK_ERROR'

export const TOGGLE_TASK_STATUS = 'TOGGLE_TASK_STATUS'
export const TOGGLE_TASK_STATUS_SUCCESS = 'TOGGLE_TASK_STATUS_SUCCESS'
export const TOGGLE_TASK_STATUS_ERROR = 'TOGGLE_TASK_STATUS_ERROR'

export const EDIT_TASK_NAME = 'EDIT_TASK_NAME'
export const EDIT_TASK_NAME_SUCCESS = 'EDIT_TASK_NAME_SUCCESS'
export const EDIT_TASK_NAME_ERROR = 'EDIT_TASK_NAME_ERROR'

export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'